[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tctk"
version = "0.3.3"
description = "A collection of mini tools."
license = { text = "GPL-3.0" }
authors = [
    { name = "Tam Tran", email = "tam.c.tran@outlook.com" }
]
urls = { Homepage = "https://github.com/nhgritctran/tctk" }
dependencies = [
    "connectorx",
    "duckdb",
    "google-cloud-bigquery",
    "huggingface_hub",
    "matplotlib>=3.5",
    "polars",
    "pyarrow",
    "rapidfuzz",
    "striprtf",
    "beautifulsoup4",
    "requests",
    "tableone",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
tctk = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "tctk",
]
