[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tctk"
version = "0.2.13"
description = "A collection of mini tools."
license = { text = "GPL-3.0" }
authors = [
    { name = "Tam Tran", email = "tam.c.tran@outlook.com" }
]
urls = { Homepage = "https://github.com/nhgritctran/tctk" }
dependencies = [
    "connectorx",
    "duckdb",
    "google-cloud-bigquery",
    "huggingface_hub",
    "polars",
    "pyarrow",
    "rapidfuzz",
    "requests",
    "tableone",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]
